### ISSUE TITLE
Using library from node

### ISSUE THREAD

**Issue by gilles-hemmerle** [alephium/alephium-js#47]
The library is working great when imported into a react project.

Although when importing it into a **node** project, it leads to the following errors :

**import style `import { walletImport } from "alephium-js"` returns this error :**

```
gillesh@gilles-systemproductname:~/Documents/development/test/import-alph-j$ node app.js 
file:///home/gillesh/Documents/development/test/import-alph-j/app.js:3
import { walletImport } from "alephium-js"
         ^^^^^^^^^^^^
SyntaxError: The requested module 'alephium-js' does not provide an export named 'walletImport'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```
**require style `const walletImport = require("alephium-js").walletImport;` throws this error :**

```
gillesh@gilles-systemproductname:~/Documents/development/test/import-alph-j$ node app.js 
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/gillesh/Documents/development/test/import-alph-j/node_modules/alephium-js/dist/lib/index.js
require() of ES modules is not supported.
require() of /home/gillesh/Documents/development/test/import-alph-j/node_modules/alephium-js/dist/lib/index.js from /home/gillesh/Documents/development/test/import-alph-j/app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/gillesh/Documents/development/test/import-alph-j/node_modules/alephium-js/package.json.
```

**How to reproduce :**

- File package.json:

```json
{
  "name": "import-alph-js",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "alephium-js": "^1.0.9"
  }
}
```
- FIle app.js:

```js
import { walletImport } from "alephium-js"
```

- Command to run:

```
node app.js
```

Reproductible with either node 12 or 14

**Comment by gilles-hemmerle** [comment]
It seems that removing type: "module" from your package.json fix the issue in node. Although, I don't know what it would impact in other projects using your library. In the mean type, I forked the project and removed this option in my version.

**Comment by nop33** [comment]
Hello @gilles-hemmerle , thanks for the report. I am looking into the issue.

**Comment by gilles-hemmerle** [comment]
Thanks, do you konw when there will be a new version on npmjs?

**Comment by nop33** [comment]
Check again in a couple minutes, the CI will have finished publishing the `v1.0.10`.
